all="All"
work="work"
an="and"
no="no"
play="play"
makes="makes"
jack="Jack"
a="a"
dull="dull"
boy="boy"
print(all+" "+work+" "+an+" "+no+" "+play+" "+makes+" "+jack+" "+a+" "+dull+" "+boy+".")